=== deegree/deegree-ogcapi/deegree-ogcapi-features/src/main/resources/META-INF/schemas/services/oaf/3.4.0/oaf_configuration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.deegree.org/services/oaf"
        xmlns:oaf="http://www.deegree.org/services/oaf"
        elementFormDefault="qualified" xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" jaxb:version="2.1">
  <annotation>
    <appinfo>
      <jaxb:schemaBindings>
        <jaxb:package name="org.deegree.services.jaxb.oaf"/>
      </jaxb:schemaBindings>
    </appinfo>
  </annotation>

  <element name="deegreeOAF">
    <complexType>
      <sequence>
        <element name="FeatureStoreId" minOccurs="0" maxOccurs="unbounded" type="string"/>
        <element name="QueryCRS" type="string" minOccurs="0" maxOccurs="unbounded" />
        <element name="DateTimeProperties" minOccurs="0">
          <complexType>
            <sequence>
              <element name="DateTimeProperty" type="oaf:DateTimePropertyType" maxOccurs="unbounded"/>
            </sequence>
          </complexType>
        </element>
        <element name="ServiceMetadata" type="oaf:ServiceMetadataType" minOccurs="0"/>
      </sequence>
      <attribute name="configVersion" use="required">
        <simpleType>
          <restriction base="string">
            <enumeration value="3.4.0"/>
          </restriction>
        </simpleType>
      </attribute>
    </complexType>
  </element>

  <complexType name="DateTimePropertyType">
    <sequence>
      <element name="FeatureTypeName" type="QName"/>
      <element name="PropertyName" type="QName"/>
    </sequence>
  </complexType>

  <complexType name="ServiceMetadataType">
    <sequence>
      <element name="MetadataURL" minOccurs="1" maxOccurs="unbounded">
        <complexType>
          <simpleContent>
            <extension base="string">
              <attribute name="format" type="string" />
            </extension>
          </simpleContent>
        </complexType>
      </element>
    </sequence>
  </complexType>

</schema>

=== deegree/deegree-ogcapi/deegree-ogcapi-features/src/main/resources/META-INF/schemas/services/oaf/3.4.0/example.xml
<deegreeOAF configVersion="3.4.0"
            xmlns="http://www.deegree.org/services/oaf"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://www.deegree.org/services/oaf oaf_configuration.xsd">

  <FeatureStoreId>test</FeatureStoreId>

  <!-- First CRS must be http://www.opengis.net/def/crs/OGC/1.3/CRS84 to be conform to OGC API Features Core -->
  <QueryCRS>http://www.opengis.net/def/crs/OGC/1.3/CRS84</QueryCRS>
  <QueryCRS>EPSG:4326</QueryCRS>
  <QueryCRS>EPSG:25832</QueryCRS>

  <DateTimeProperties>
    <DateTimeProperty>
      <FeatureTypeName xmlns:app="http://www.deegree.org/app">app:FeatureType</FeatureTypeName>
      <PropertyName xmlns:app="http://www.deegree.org/app">app:datetime</PropertyName>
    </DateTimeProperty>
  </DateTimeProperties>

  <ServiceMetadata>
    <MetadataURL format="application/xml">http://metaver?service=CSW&amp;request=GetRecordById&amp;version=2.0.2&amp;id=89362</MetadataURL>
    <MetadataURL format="text/html">http://localhost:8080/linkZuHTml/89362</MetadataURL>
  </ServiceMetadata>

</deegreeOAF>
